name: Scrape Website

on:
  schedule:
    - cron: "*/20 * * * *" # Runs every 20 mins
  workflow_dispatch: # Allows manual trigger from GitHub UI

permissions:
  contents: write

jobs:
  scrape-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch Hacker News
        run: curl https://news.ycombinator.com > hacker-news.html

      - name: Commit data
        run: |
          git config --global user.name 'Scrape Bot'
          git config --global user.email 'scrape.bot@example.com'
          git add hacker-news.html
          git commit -m ":robot: scraped" || echo "No changes to commit"
          git push
